default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch("SUPABASE_DB_URL") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("SUPABASE_DB_HOST") %>
  port: <%= ENV.fetch("SUPABASE_DB_PORT") %>
  database: <%= ENV.fetch("SUPABASE_DB_NAME") %>
  username: <%= ENV.fetch("SUPABASE_DB_USER") %>
  password: <%= ENV.fetch("SUPABASE_DB_PASSWORD") %>
  sslmode: require

development:
  <<: *default
  database: meta_development

test:
  <<: *default
  database: meta_test

production:
  primary: &primary_production
    <<: *default
    database: meta_production
    username: meta
    password: <%= ENV["META_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: meta_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: meta_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: meta_production_cable
    migrations_paths: db/cable_migrate
